version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto25
  pre_build:
    commands:
      - java -version
      - mvn -version
  build:
    commands:
      - mvn clean package -DskipTests

artifacts:
  files:
    - 'target/*.jar'
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'